### ISSUE TITLE
Add Support iPad Pro (11 Inch) (4th generation)

### ISSUE THREAD

**Issue by X901** [AvdLee/RocketSimApp#241]
I just update to Xcode 14
on iPhone Pro all models it recognize it, on iPad it doesn't show app options
I just can Record using app button on menu bar

**Comment by AvdLee** [comment]
Similar to #237, this will be fixed in the next major 9.0.0 release!

**Comment by AvdLee** [comment]
Fixed in RocketSim 9.0.0 which will be released soon!

**Comment by navoshta** [comment]
> Fixed in RocketSim 9.0.0 which will be released soon!

I'm running RocketSim 9.3.0 and it still doesn't seem to recognise iPad Pro (11 Inch) (4th generation) sim (Xcode 14.2).

**Comment by AvdLee** [comment]
Thanks for reporting, I'll look into it!

**Comment by AvdLee** [comment]
Reproduced and fixing, fixed in 9.4!

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/4329185/216127995-aaa2819b-b009-4722-ba1a-9a1d88dd93dd.png">
