### ISSUE TITLE
RocketSim 9.3.0 (134) fails to control the simulator with Xcode 14.2 (14C18) and macOS Ventura 13.2

### ISSUE THREAD

**Issue by rpassis** [AvdLee/RocketSimApp#266]
**Describe the bug**

Recently RocketSim has been pretty unstable for me. 
The version I'm currently using is 9.3.0 (134) alongside Xcode 14.2 (14C18)

<img width="659" alt="CleanShot 2023-02-02 at 17 23 26@2x" src="https://user-images.githubusercontent.com/387079/216258396-703fbe2d-fffb-4f48-b035-acf398cdaebe.png">

**To Reproduce**

I have included a video below but the short description of this is that with the Simulator open, if I open RocketSim I am unable to perform any actions on said simulator. As per the video, no overlay is displayed and none of the screen recording actions actually work. 

At some point during the day I was getting an error saying "No simulator detected make sure it is running" (it was running) but that no longer appears, it just doesn't want to work. I've restarted Xcode, Simulator and my Mac to no avail.

I should say RocketSim was working fine before and then it started with some weird issues where the overlay would stay on screen even if the simulator was not on the foreground. Whenever that happened I had to close RocketSim and reopen it for it to work again. This may have coincided with updating my Macbook to Ventura 13.2 but I'm not positive that this is the case.

**Expected behavior**

RocketSim should work as advertised :) 

**Screenshots**

https://share.cleanshot.com/8ts2G067

**Desktop (please complete the following information):**

Apple M1 Pro
Ventura 13.2 (22D49)

**Additional context**

**Comment by AvdLee** [comment]
@rpassis thanks for reporting in! I've added animations and a moving window that potentially resulted in this. I released 9.4 yesterday, could you try that version and see if it improves?

If not, would you mind pressing that "Report a bug" button from your image and send me a Diagnostics Report? I'd love to make this ticket a priority since performance issues are the last thing I want!

**Comment by rpassis** [comment]
Sure thing! FYI after updating to 9.4.0 the problem persists, here's a screenshot of what I get after clicking on start MP4 recording:

<img width="840" alt="CleanShot 2023-02-03 at 11 12 03@2x" src="https://user-images.githubusercontent.com/387079/216487233-fb019e51-fe50-4948-aabd-f9556c2d9937.png">

No other actions work, and the floating window is not visible either.

For some reason, I can't use the Report a bug function - when I tap on it it opens an empty page of Microsoft Edge browser (FWIW that is not even my default browser)

**Comment by rpassis** [comment]
I'm curious to see if reverting to an older version would fix any of these issues. Do you have an archive of older versions that I can try out and report back here?

**Comment by AvdLee** [comment]
> For some reason, I can't use the Report a bug function - when I tap on it it opens an empty page of Microsoft Edge browser (FWIW that is not even my default browser)

You can right-click that button and save it to desktop. The button probably fails since you don't have the native Mac mail installed.

> I'm curious to see if reverting to an older version would fix any of these issues. My work computer is heavily restricted via MDM profiles so it would be good to verify whether this is a change that may have occurred or my side rather than yours.
>
> Do you have an archive of older versions that I can try out and report back here?

Let's try the Diagnostics Report first. I'm pretty convinced I'll be able to find the root cause! For your context: both floating window and recording logic are based on the same underlying mechanism of detecting open Simulator windows. If one fails, the other fails as well

**Comment by rpassis** [comment]
Sounds good, here's the report as requested. Could you perhaps download and then remove the attachment from this comment when done. I don't think there is any sensitive information being leaked from what I can see but just to be on the safe side.

[Diagnostics-Report.html.zip](https://github.com/AvdLee/RocketSimApp/files/10610034/Diagnostics-Report.html.zip)

Thanks!

Rog

**Comment by AvdLee** [comment]
@rpassis I've removed it for you. I'll be looking into this later this week!

**Comment by AvdLee** [comment]
Alright, I tried finding the cause, but it's hard to tell the exact cause. Could you try the following:

- Open preferences
- Select Xcode again using other:

![CleanShot 2023-02-06 at 19 32 02@2x](https://user-images.githubusercontent.com/4329185/217055759-27b422e8-abdd-430b-bd46-f65c8eba33d2.jpg)

Also, to be sure: 
- you're not using a symlink to Xcode.app, right? Is it really inside your applications folder?
- What Command line tool did you select? See inside Xcode's preferences:
![CleanShot 2023-02-06 at 19 32 53@2x](https://user-images.githubusercontent.com/4329185/217055934-fc945739-d015-42a6-8b3a-6dacd8d482f6.jpg)

**Comment by rpassis** [comment]
Hey FYI I didn't end up doing any of the above but to answer your question:

1) Only one copy of Xcode currently installed, and definitely not symlinked
2) `xcode-select -p` outputs `/Applications/Xcode.app/Contents/Developer`

After updating to 9.5.0 (139) the floating window is back, and I can also interact with the simulator as expected so it's looking good so far. I'll close this issue for now but will let you know if it pops up again.

Thanks for your help!
Rog

**Comment by AvdLee** [comment]
Thanks for reporting back and great to hear it's all working as expected again! I still wonder what was wrong before, but as long as it works... 🙏😁
