### ISSUE TITLE
Invisible RocketSim window breaks SCContentSharingPicker for window sharing/recording

### ISSUE THREAD

**Issue by renssies** [AvdLee/RocketSimApp#490]
**Describe the bug**
RocketSim seems to have an always on top invisible window. However this window is included in the SCContentSharingPicker of the ScreenCaptureKit framework. Since the window is always on top this means you can't select any other windows using this picker.

Safari is one of the apps using ScreenCaptureKit and the SCContentSharingPicker.

**To Reproduce**
1. Open Safari
2. Go to any video call platform that supports screen sharing (I used Google meet)
3. Enter a meeting and share the screen
4. Safari will prompt if you want to share a screen or share a window. Choose share window
5. Try to share a window that is not RocketSim

**Expected behavior**
For the invisible RocketSim window to not be selectable for ScreenCaptureKit. 
I believe setting the `sharingType` on an NSWindow disables it for screen sharing.

**Screenshots**
![Screenshot 2024-03-29 at 16 14 36](https://github.com/AvdLee/RocketSimApp/assets/830094/2fd0c141-cf70-4184-8ec5-67a8aa4721c4)

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version: 14.4.1
 - Machine: Mac Mini with 1440p external dell monitor
 - Processor: M2 Pro

**Additional context**
A video of the problem. In this I try to screen share just the Bambu Studio app (green icon).
https://youtu.be/S6nXj_zISVI

**Workaround**
Hold on the green fullscreen icon of a window and choose "Share window with X"

**Comment by AvdLee** [comment]
Ouch, this is not good! Thanks for the detail report and even the coding fix that should solve this. I'll try to push this into the next build!

**Comment by AvdLee** [comment]
This will be fixed in 12.9.0

**Comment by renssies** [comment]
The issue is back in 12.11. 

I've resorted to only launching RocketSim when I only need it.

**Comment by AvdLee** [comment]
Just want to let you know we've fixed this once again. There's an update coming next week with even more improvements
