### ISSUE TITLE
Impossible to select Xcode under macOS Sequoia

### ISSUE THREAD

**Issue by swipip** [AvdLee/RocketSimApp#587]
**Describe the bug**
Randomly RocketSim "loses" xcode. I get prompt again to select Xcode from the applications folder. When doing so I keep going back to the onboarding screen where nothing happens. 

I am basically stuck on this page. 

![image](https://github.com/user-attachments/assets/f36f0671-2f73-46a5-95df-c2544f52ab56){width:400}

**To Reproduce**
1. Launch rocket sim
2. click on in some network call cell under the network recording panel
3. rocket sim stops and asks to select xcode

**Expected behavior**
I can navigate network calls.

**Screenshots**
![image](https://github.com/user-attachments/assets/769c21b8-4ba9-4419-a962-024ebc7a9e9f){width=400}

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 15.0

**Additional context**
I only have on Xcode installed, named Xcode.

**Comment by AvdLee** [comment]
@swipip thanks for reaching out and sorry for this inconvenience! Can you report an issue via Settings → About → Report an Issue? 

I'm happy to dive deeper into this!

**Comment by griffinshuth** [comment]
![Screenshot 2024-09-30 at 7 37 42 AM](https://github.com/user-attachments/assets/e14f43ba-c0f9-4a3d-aee9-966a4bba3282)
im facing the same issue the only way for me to get this to work is i have to restart my computer RocketSim it seems like it is only lasting a couple hours before this happens.  and as you can see from the screenshot i have RocketSim loaded but then it loses Xcode and is frozen pretty much i cant even report an issue in settings because of it.

**Comment by swipip** [comment]
Thanks for the reply, I can't access settings neither, the modal popup blocks any other interaction.

**Comment by AvdLee** [comment]
@griffinshuth @swipip dang, this is really odd! Also because it doesn't happen to all users, so it must be something specific to both of you. 

Could you please try to send me a Diagnostics Report via Settings → About → Report an Issue as soon as Xcode selection works again?

That way, I'm much better able to get any sense of what's going on under the hood.

**Comment by AvdLee** [comment]
I've managed to find the root cause of this and it appears to be a macOS bug that is going to be fixed in 15.1: https://forums.developer.apple.com/forums/thread/764435

For now, a restart of your machine should help solve the issue. I recommend updating I once macOS 15.1 becomes available. 

Let me know if you have any questions!

**Comment by Craz1k0ek** [comment]
Possibly already fixed with `15.0.1 (24A348)`

**Comment by azalan** [comment]
I'm on 15.0.1, and I still have issues. Let's hope that 15.1 will fix it.

**Comment by AvdLee** [comment]
> I'm on 15.0.1, and I still have issues. Let's hope that 15.1 will fix it.

Yes, other users confirmed this. I really hope for 15.1 to fix this!

**Comment by AvdLee** [comment]
I've just submitted 12.11.12 with a fix for this to at least make Xcode selection work using an in-memory back-up when the security scope doesn't work. Let me know if that solves it for you meanwhile!

**Comment by AvdLee** [comment]
Closing this issue as it's both solved as far as I can and solved in the latest macOS update.
